# Generated by Django 4.1.2 on 2022-10-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='time',
            new_name='date',
        ),
    ]
