# Generated by Django 4.1.2 on 2022-11-07 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.template.defaultfilters


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_user_comments_auction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'get_latest_by': django.template.defaultfilters.date},
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_category', to='auctions.category'),
        ),
    ]
