# Generated by Django 4.1.2 on 2022-11-09 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bids_options_alter_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='auction_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
